# **Import Libraries**

In [98]:
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import matplotlib.pyplot as plt
import numpy as np
from os import listdir
from os.path import join
import cv2
import pandas
import os
import random

# **Load DataSet**

In [54]:
# Identify folders
data = "/content/drive/MyDrive/Datasets/Flowers Ds/flowers"
# List out the directories inside the main input folder
folders = os.listdir(data)
print(folders)

['dandelion', 'tulip', 'rose', 'daisy', 'sunflower']


In [59]:
# Import the images and resize them to a 128*128 size
# Also generate the corresponding labels

image_names = []
train_labels = []
train_images = []

size = 64,64

for folder in folders:
    for file in os.listdir(os.path.join(data,folder)):
        if file.endswith("jpg"):
            image_names.append(os.path.join(data,folder,file))
            train_labels.append(folder)
            img = cv2.imread(os.path.join(data,folder,file))
            im = cv2.resize(img,size)
            train_images.append(im)
        else:
          break           

In [106]:
# Transform the image array to a numpy type
train = np.array(train_images)
train.shape

(4086, 64, 64, 3)

In [105]:
# Reduce the RGB values between 0 and 1
train = train.astype('float32') / 255.0


In [107]:
# Extract the labels
label_dummies = pandas.get_dummies(train_labels)
labels =  label_dummies.values.argmax(1)

In [108]:
pandas.unique(train_labels)

array(['dandelion', 'tulip', 'rose', 'daisy', 'sunflower'], dtype=object)

In [110]:
pandas.unique(labels) , pandas.unique(images_labels)

array([1, 4, 2, 0, 3])

In [71]:
# Shuffle the labels and images randomly for better results

union_list = list(zip(train, labels))
random.shuffle(union_list)
train,labels = zip(*union_list)

# Convert the shuffled list to numpy array type

train = np.array(train)
labels = np.array(labels)

In [101]:
x =train
y=labels
pandas.unique(y)

array([1, 0, 4, 2, 3])

# **Convert Labels to Categorical - One hot encoding**

In [102]:
#one hot encode target values
Y = to_categorical(y)
Y[0]

array([0., 1., 0., 0., 0.], dtype=float32)

# **Define Model and Fit function**

In [103]:
# define model
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(x.shape[1], x.shape[2], x.shape[3])))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(5, activation='softmax'))
# compile model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [104]:
history = model.fit(x, Y, epochs = 20 , batch_size = 200)

Epoch 1/20
21/21 [==============================] - 19s 862ms/step - loss: 1.5497 - accuracy: 0.3204
Epoch 2/20
21/21 [==============================] - 18s 868ms/step - loss: 1.1971 - accuracy: 0.4843
Epoch 3/20
21/21 [==============================] - 18s 865ms/step - loss: 1.0967 - accuracy: 0.5456
Epoch 4/20
21/21 [==============================] - 18s 872ms/step - loss: 1.0626 - accuracy: 0.5708
Epoch 5/20
21/21 [==============================] - 18s 868ms/step - loss: 0.9872 - accuracy: 0.6275
Epoch 6/20
21/21 [==============================] - 18s 867ms/step - loss: 0.9358 - accuracy: 0.6345
Epoch 7/20
21/21 [==============================] - 18s 869ms/step - loss: 0.8716 - accuracy: 0.6627
Epoch 8/20
21/21 [==============================] - 18s 869ms/step - loss: 0.8323 - accuracy: 0.6824
Epoch 9/20
21/21 [==============================] - 18s 867ms/step - loss: 0.8178 - accuracy: 0.6910
Epoch 10/20
21/21 [==============================] - 18s 869ms/step - loss: 0.7343 - accura